#!/bin/bash
# ROLL-BROWNIAN ABLATION SCOUT — is there ANY motor-generated twirl?
#
# With chanMask[2]=0 the roll DOF has NO thermal input: gamma_roll*dtheta/dt = tau_motor exactly.
# Any sustained trend in theta(t) is motor-generated BY CONSTRUCTION. The ON arm is the matched control
# and, equally important, the avgBound cross-check: if ablating roll noise moves recruitment, the
# ablation is perturbing the thing it is meant to isolate (roll sets which helical sites face the bed).
#
# NONCANONICAL / NOT FDT-consistent for the roll DOF. Diagnostic only, never production.
# Scene: d500, eta=0.10 (Campaign 2 reference point), dt 1.25e-6, T=0.25 s = 200k steps.
cd /home/jba/Code/SoftBox
OUT=/home/jba/Code/SoftBox/RUN_LOGS/motor_audit/campaigns_2026-08/ROLL_ABLATION
mkdir -p "$OUT"; R=$OUT/REPORT.txt
say(){ echo "[$(date '+%m-%d %H:%M')] $*" | tee -a $R; }
STEPS=200000; DT=1.25e-6; W=2
say "ROLL-BROWNIAN ABLATION SCOUT — d500 eta=0.10 dt=$DT steps=$STEPS (T=0.25 s), workers=$W"
say "  arm OFF: -norollbrownian  (chanMask[2]=0, roll thermal torque removed)"
say "  arm ON : canonical control (identical in every other respect)"
for S in 20260901 20260902 20260903; do
  ./scripts/run_site_normal_long_glide.sh -run -nohires -noviz -density 500 -seed $S -filx 2.30 \
     -eta 0.10 -dt $DT -steps $STEPS -workers $W -norollbrownian -out $OUT/off_s$S > $OUT/off_s$S.log 2>&1 &
  ./scripts/run_site_normal_long_glide.sh -run -nohires -noviz -density 500 -seed $S -filx 2.30 \
     -eta 0.10 -dt $DT -steps $STEPS -workers $W               -out $OUT/on_s$S  > $OUT/on_s$S.log  2>&1 &
done
wait
say "runs complete — analysing theta(t)"
python3 scripts/roll_ablation_analyse.py "$OUT" 2>&1 | tee -a $R
say "DONE."
